app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/<int:recipe_id>/toggle-favorite/', views.toggle_favorite, name='toggle_favorite'),
    path('recipe/<int:recipe_id>/chef_ai/', views.chef_ai_assistant, name='chef_ai_assistant'),
    path('recipe/create/', views.create_recipe, name='create_recipe'),
    path('login/', views.login_view, name='login'),
    path('login/done', views.login_done, name='login_done'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/', views.change_password_view, name='change_password'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('app.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/global/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} | Recipedia</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet" />
    <link href="{% static "global/images/favicon.png" %}" rel="icon" />
    <link href="{% static "global/css/reset.css" %}" rel="stylesheet"/>
    <link href="{% static "global/css/style.css" %}" rel="stylesheet"/>
    <style>
      .main-content {
        top: 0px;
      }
    </style>
    {% block head %}{% endblock %}
    <script src="https://unpkg.com/htmx.org@2.0.4/dist/htmx.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  </head>
  <body>
    <main class="main-content">
    {% block body %}{% endblock body %}
    </main>
  </body>
</html>

templates/global/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} | Recipedia</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet" />
    <link href="{% static "global/images/favicon.png" %}" rel="icon" />
    <link href="{% static "global/css/reset.css" %}" rel="stylesheet"/>
    <link href="{% static "global/css/style.css" %}" rel="stylesheet"/>
    {% block head %}{% endblock %}
    <script src="https://unpkg.com/htmx.org@2.0.4/dist/htmx.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  </head>
  <body>
    <header class="header">
      <a href="{% url 'app:home' %}" title="Discover incredible recipes for all tastes in one place">
      <div class="logo">
        <div class="logo-icon">
          <img src="{% static "global/images/white-logo.png" %}">
        </div>
        Recipedia
      </div>
      </a>

      <nav class="nav">
        <a href="{% url 'app:home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}" title="Website Home Page">Home</a>
        <a href="{% url 'app:about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}" title="Website Information Page">About</a>
      </nav>
      
      <div class="account-menu">
        <div id="account-trigger" class="account-trigger" title="Click to access your account">
          <i class="fa-solid fa-circle-user fa-2xl" style="color: #ffffff;"></i>
        </div>
        
        <div id="account-dropdown" class="account-dropdown">
          {% if user.is_authenticated %}
            <div class="dropdown-header">
              <div class="user-info">{{ user.username }}</div>
              {% if user.email %}
                <div class="user-email">{{ user.email }}</div>
              {% endif %}
            </div>
            <div class="dropdown-menu">
              {% if user.is_staff %}
              <a href="{% url 'admin:index' %}" class="dropdown-item">
                <i class="fa-solid fa-screwdriver-wrench"></i>
                <span>Administrative Area</span>
              </a>
              {% endif %}
              <a href="{% url 'app:change_password' %}" class="dropdown-item">
                <i class="fa-solid fa-key"></i>
                <span>Change Password</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'app:logout' %}" class="dropdown-item">
                <i class="fa-solid fa-sign-out-alt"></i>
                <span>Logout</span>
              </a>
            </div>
          {% else %}
            <div class="dropdown-menu">
              <a href="{% url 'app:register' %}" class="dropdown-item">
                <i class="fa-solid fa-user"></i>
                <span>Create Account</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'app:login' %}" class="dropdown-item">
                <i class="fa-solid fa-sign-in-alt"></i>
                <span>Login</span>
              </a>
            </div>
          {% endif %}
        </div>
      </div>
    </header>
    
    <main class="main-content">
    {% block body %}{% endblock body %}
    </main>

    <script src="{% static "global/js/script.js" %}"></script>
  </body>
</html>